### ISSUE TITLE
Running on AWS/DocumentDB

### ISSUE THREAD

**Issue by DaveFPM** [growthbook/growthbook#1236]
Hi, I'm trying to run this on AWS/DocumentDB, but I am getting this error, is there anything I can do to make this work?

```
[root@ip-10-0-2-218 log]# docker logs 6cca415f2480
yarn run v1.22.19
$ wsrun -p '*-end' -m start
back-end
 | $ node dist/server.js
front-end
 | $ next start
 | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
back-end
 | {"level":30,"time":1682630885500,"pid":57,"hostname":"6cca415f2480","msg":"No config.yml file. Using MongoDB instead to store data sources, metrics, and dimensions."}
 | {"level":30,"time":1682630886259,"pid":57,"hostname":"6cca415f2480","msg":"Back-end is running at http://localhost:3100 in development mode. Press CTRL-C to stop"}
 | /usr/local/src/app/node_modules/mongodb/lib/utils.js:698
 |           throw error;
 |           ^
 | 
 | MongoError: Implicit collection creation not supported when creating indexes
 |     at MessageStream.messageHandler (/usr/local/src/app/node_modules/mongodb/lib/cmap/connection.js:299:20)
 |     at MessageStream.emit (node:events:513:28)
 |     at MessageStream.emit (node:domain:489:12)
 |     at processIncomingData (/usr/local/src/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
 |     at MessageStream._write (/usr/local/src/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
 |     at writeOrBuffer (node:internal/streams/writable:391:12)
 |     at _write (node:internal/streams/writable:332:10)
 |     at MessageStream.Writable.write (node:internal/streams/writable:336:10)
 |     at TLSSocket.ondata (node:internal/streams/readable:754:22)
 |     at TLSSocket.emit (node:events:513:28)
 |     at TLSSocket.emit (node:domain:489:12)
 |     at addChunk (node:internal/streams/readable:315:12)
 |     at readableAddChunk (node:internal/streams/readable:289:9)
 |     at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
 |     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
 | Emitted 'error' event on Agenda instance at:
 |     at /usr/local/src/app/node_modules/agenda/dist/agenda/db-init.js:28:18
 |     at /usr/local/src/app/node_modules/mongodb/lib/utils.js:695:9
 |     at executeCallback (/usr/local/src/app/node_modules/mongodb/lib/operations/execute_operation.js:65:7)
 |     at /usr/local/src/app/node_modules/mongodb/lib/operations/create_indexes.js:126:9
 |     at /usr/local/src/app/node_modules/mongodb/lib/operations/command_v2.js:103:9
 |     at /usr/local/src/app/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
 |     at handleOperationResult (/usr/local/src/app/node_modules/mongodb/lib/core/sdam/server.js:567:5)
 |     at MessageStream.messageHandler (/usr/local/src/app/node_modules/mongodb/lib/cmap/connection.js:299:11)
 |     at MessageStream.emit (node:events:513:28)
 |     [... lines matching original stack trace ...]
 |     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
 |   code: 85,
 |   errorUUID: 'dd0860e9-d091-4327-8761-efae050e400d',
 |   ok: 0
 | }
 | error Command failed with exit code 1.
 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | `yarn start` failed with exit code 1
```

**Comment by RomanHotsiy** [comment]
@DaveFPM did you have any success running it on AWS/DocumentDB?

**Comment by yepher** [comment]
I think that is a connection issue. Did you install the [PEM file](https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem) and set `tls=true`? This worked for me: 

### Dockerfile:

```
FROM growthbook/growthbook:2.4.0

ENV GBHOME=/usr/local/src/app
WORKDIR $GBHOME

RUN apt-get update && \
  apt-get install -y curl telnet && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN wget https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem

EXPOSE 3000
EXPOSE 3100
```

### MONGDB_URI? 

```
mongodb://<docDbUser>:<docDBPassword>@<docDBHostname>:27017/growthbook?authSource=admin&directConnection=true&serverSelectionTimeoutMS=5000&tls=true&tlsAllowInvalidHostnames=true&tlsCAFile=%2Fusr%2Flocal%2Fsrc%2Fapp%2Fglobal-bundle.pem&retryWrites=False
```

I think you can remove `tlsAllowInvalidHostnames` but that is for my local instance that was using port forwarding through a tunnel for testing.

**Comment by alyssamichelle** [comment]
**Our audit of stale tickets suggests this may already be resolved, or no longer applicable, on the current version — but we couldn't prove it from the code alone.** @DaveFPM could you confirm whether you still see this on the latest release? @tzjames assigning to you to make the final call once they reply (or after a couple of weeks of silence).

**Why:** Docs now list AWS DocumentDB (and Azure DocumentDB, FerretDB) as supported managed options (docs/self-host/production.mdx 'MongoDB' section; docs/self-host.mdx) and code explicitly avoids features DocumentDB/Cosmos reject (comments in packages/back-end/src/models/BaseModel.ts ~797 and FeatureRevisionModel.ts ~2319). There is no dedicated DocumentDB guide (TLS bundle, retryWrites=false) and the original Agenda 'Implicit collection creation not supported' error has no specific fix in the repo (agenda ^5.0.0, mongodb ^4.17.2). A community comment showed it works with tls + CA bundle in the URI. jdorn asked in Aug 2025 whether this is still an issue.

Suggested next step: Ask for confirmation on latest image; if it works with the documented URI flags, add a short DocumentDB section to docs/self-host/production.mdx (TLS CA bundle, retryWrites=false) and close.

If it turns out to be fixed, please close with a note. If it stays open, please update the labels to reflect current state (keep `bug`/`enhancement` accurate, add `roadmap` if it's planned, drop stale ones like `2024-tracked`).

<sub>Part of a sweep of 223 long-quiet issues audited against `main` (Sept 2026). Ping @alyssamichelle if the evidence looks wrong.</sub>
