### ISSUE TITLE
[Bug] Validate OpenAPI spec

### ISSUE THREAD

**Issue by tinahollygb** [growthbook/growthbook#1269]
When running the OpenAPI spec (https://api.growthbook.io/api/v1/openapi.yaml) through a validator, we get errors.

<details>
<summary><b>OpenAPI validation errors</b></summary>

```
Swagger schema validation failed.
  #/paths/~1features/get/responses/200 must have required property 'description'
  #/paths/~1features/get/responses/200 must match "else" schema
  #/paths/~1features~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1features~1{id}/get/responses/200 must match "else" schema
  #/paths/~1features~1{id}~1toggle/post/responses/200 must have required property 'description'
  #/paths/~1features~1{id}~1toggle/post/responses/200 must match "else" schema
  #/paths/~1projects/get/responses/200 must have required property 'description'
  #/paths/~1projects/get/responses/200 must match "else" schema
  #/paths/~1projects~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1projects~1{id}/get/responses/200 must match "else" schema
  #/paths/~1dimensions/get/responses/200 must have required property 'description'
  #/paths/~1dimensions/get/responses/200 must match "else" schema
  #/paths/~1dimensions~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1dimensions~1{id}/get/responses/200 must match "else" schema
  #/paths/~1segments/get/responses/200 must have required property 'description'
  #/paths/~1segments/get/responses/200 must match "else" schema
  #/paths/~1segments~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1segments~1{id}/get/responses/200 must match "else" schema
  #/paths/~1sdk-connections/get/responses/200 must have required property 'description'
  #/paths/~1sdk-connections/get/responses/200 must match "else" schema
  #/paths/~1sdk-connections~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1sdk-connections~1{id}/get/responses/200 must match "else" schema
  #/paths/~1data-sources/get/responses/200 must have required property 'description'
  #/paths/~1data-sources/get/responses/200 must match "else" schema
  #/paths/~1data-sources~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1data-sources~1{id}/get/responses/200 must match "else" schema
  #/paths/~1experiments/get/responses/200 must have required property 'description'
  #/paths/~1experiments/get/responses/200 must match "else" schema
  #/paths/~1experiments~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1experiments~1{id}/get/responses/200 must match "else" schema
  #/paths/~1experiments~1{id}~1results/get/responses/200 must have required property 'description'
  #/paths/~1experiments~1{id}~1results/get/responses/200 must match "else" schema
  #/paths/~1metrics/get/responses/200 must have required property 'description'
  #/paths/~1metrics/get/responses/200 must match "else" schema
  #/paths/~1metrics/post/responses/200 must have required property 'description'
  #/paths/~1metrics/post/responses/200 must match "else" schema
  #/paths/~1metrics~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1metrics~1{id}/get/responses/200 must match "else" schema
  #/paths/~1experiments~1{id}~1visual-changesets/get/parameters/0 must NOT have unevaluated properties
  #/paths/~1experiments~1{id}~1visual-changesets/get/parameters/0 must match "else" schema
  #/paths/~1experiments~1{id}~1visual-changesets/get/responses/200 must have required property 'description'
  #/paths/~1experiments~1{id}~1visual-changesets/get/responses/200 must match "else" schema
  #/paths/~1visual-changesets~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1visual-changesets~1{id}/get/responses/200 must match "else" schema
  #/paths/~1visual-changesets~1{id}/put/responses/200 must have required property 'description'
  #/paths/~1visual-changesets~1{id}/put/responses/200 must match "else" schema
  #/paths/~1visual-changesets~1{id}~1visual-change/post/responses/200 must have required property 'description'
  #/paths/~1visual-changesets~1{id}~1visual-change/post/responses/200 must match "else" schema
  #/paths/~1visual-changesets~1{id}~1visual-change~1{visualChangeId}/put/responses/200 must have required property 'description'
  #/paths/~1visual-changesets~1{id}~1visual-change~1{visualChangeId}/put/responses/200 must match "else" schema
  #/paths/~1saved-groups/get/responses/200 must have required property 'description'
  #/paths/~1saved-groups/get/responses/200 must match "else" schema
  #/paths/~1saved-groups/post/responses/200 must have required property 'description'
  #/paths/~1saved-groups/post/responses/200 must match "else" schema
  #/paths/~1saved-groups~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1saved-groups~1{id}/get/responses/200 must match "else" schema
  #/paths/~1saved-groups~1{id}/post/responses/200 must have required property 'description'
  #/paths/~1saved-groups~1{id}/post/responses/200 must match "else" schema
  #/paths/~1saved-groups~1{id}/delete/responses/200 must have required property 'description'
  #/paths/~1saved-groups~1{id}/delete/responses/200 must match "else" schema
  #/components/responses/Error must have required property 'description'
  #/components/responses/Error must NOT have unevaluated properties
  #/components/responses/Error must NOT have unevaluated properties
  #/components/responses/Error must NOT have unevaluated properties
  #/components/responses/Error must match "else" schema


Error: Swagger schema validation failed.
  #/paths/~1features/get/responses/200 must have required property 'description'
  #/paths/~1features/get/responses/200 must match "else" schema
  #/paths/~1features~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1features~1{id}/get/responses/200 must match "else" schema
  #/paths/~1features~1{id}~1toggle/post/responses/200 must have required property 'description'
  #/paths/~1features~1{id}~1toggle/post/responses/200 must match "else" schema
  #/paths/~1projects/get/responses/200 must have required property 'description'
  #/paths/~1projects/get/responses/200 must match "else" schema
  #/paths/~1projects~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1projects~1{id}/get/responses/200 must match "else" schema
  #/paths/~1dimensions/get/responses/200 must have required property 'description'
  #/paths/~1dimensions/get/responses/200 must match "else" schema
  #/paths/~1dimensions~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1dimensions~1{id}/get/responses/200 must match "else" schema
  #/paths/~1segments/get/responses/200 must have required property 'description'
  #/paths/~1segments/get/responses/200 must match "else" schema
  #/paths/~1segments~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1segments~1{id}/get/responses/200 must match "else" schema
  #/paths/~1sdk-connections/get/responses/200 must have required property 'description'
  #/paths/~1sdk-connections/get/responses/200 must match "else" schema
  #/paths/~1sdk-connections~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1sdk-connections~1{id}/get/responses/200 must match "else" schema
  #/paths/~1data-sources/get/responses/200 must have required property 'description'
  #/paths/~1data-sources/get/responses/200 must match "else" schema
  #/paths/~1data-sources~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1data-sources~1{id}/get/responses/200 must match "else" schema
  #/paths/~1experiments/get/responses/200 must have required property 'description'
  #/paths/~1experiments/get/responses/200 must match "else" schema
  #/paths/~1experiments~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1experiments~1{id}/get/responses/200 must match "else" schema
  #/paths/~1experiments~1{id}~1results/get/responses/200 must have required property 'description'
  #/paths/~1experiments~1{id}~1results/get/responses/200 must match "else" schema
  #/paths/~1metrics/get/responses/200 must have required property 'description'
  #/paths/~1metrics/get/responses/200 must match "else" schema
  #/paths/~1metrics/post/responses/200 must have required property 'description'
  #/paths/~1metrics/post/responses/200 must match "else" schema
  #/paths/~1metrics~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1metrics~1{id}/get/responses/200 must match "else" schema
  #/paths/~1experiments~1{id}~1visual-changesets/get/parameters/0 must NOT have unevaluated properties
  #/paths/~1experiments~1{id}~1visual-changesets/get/parameters/0 must match "else" schema
  #/paths/~1experiments~1{id}~1visual-changesets/get/responses/200 must have required property 'description'
  #/paths/~1experiments~1{id}~1visual-changesets/get/responses/200 must match "else" schema
  #/paths/~1visual-changesets~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1visual-changesets~1{id}/get/responses/200 must match "else" schema
  #/paths/~1visual-changesets~1{id}/put/responses/200 must have required property 'description'
  #/paths/~1visual-changesets~1{id}/put/responses/200 must match "else" schema
  #/paths/~1visual-changesets~1{id}~1visual-change/post/responses/200 must have required property 'description'
  #/paths/~1visual-changesets~1{id}~1visual-change/post/responses/200 must match "else" schema
  #/paths/~1visual-changesets~1{id}~1visual-change~1{visualChangeId}/put/responses/200 must have required property 'description'
  #/paths/~1visual-changesets~1{id}~1visual-change~1{visualChangeId}/put/responses/200 must match "else" schema
  #/paths/~1saved-groups/get/responses/200 must have required property 'description'
  #/paths/~1saved-groups/get/responses/200 must match "else" schema
  #/paths/~1saved-groups/post/responses/200 must have required property 'description'
  #/paths/~1saved-groups/post/responses/200 must match "else" schema
  #/paths/~1saved-groups~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1saved-groups~1{id}/get/responses/200 must match "else" schema
  #/paths/~1saved-groups~1{id}/post/responses/200 must have required property 'description'
  #/paths/~1saved-groups~1{id}/post/responses/200 must match "else" schema
  #/paths/~1saved-groups~1{id}/delete/responses/200 must have required property 'description'
  #/paths/~1saved-groups~1{id}/delete/responses/200 must match "else" schema
  #/components/responses/Error must have required property 'description'
  #/components/responses/Error must NOT have unevaluated properties
  #/components/responses/Error must NOT have unevaluated properties
  #/components/responses/Error must NOT have unevaluated properties
  #/components/responses/Error must match "else" schema

    at o (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:95564)
    at https://apitools.dev/swagger-parser/online/js/bundle.min.js:29:45042

SyntaxError: Swagger schema validation failed.
  #/paths/~1features/get/responses/200 must have required property 'description'
  #/paths/~1features/get/responses/200 must match "else" schema
  #/paths/~1features~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1features~1{id}/get/responses/200 must match "else" schema
  #/paths/~1features~1{id}~1toggle/post/responses/200 must have required property 'description'
  #/paths/~1features~1{id}~1toggle/post/responses/200 must match "else" schema
  #/paths/~1projects/get/responses/200 must have required property 'description'
  #/paths/~1projects/get/responses/200 must match "else" schema
  #/paths/~1projects~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1projects~1{id}/get/responses/200 must match "else" schema
  #/paths/~1dimensions/get/responses/200 must have required property 'description'
  #/paths/~1dimensions/get/responses/200 must match "else" schema
  #/paths/~1dimensions~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1dimensions~1{id}/get/responses/200 must match "else" schema
  #/paths/~1segments/get/responses/200 must have required property 'description'
  #/paths/~1segments/get/responses/200 must match "else" schema
  #/paths/~1segments~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1segments~1{id}/get/responses/200 must match "else" schema
  #/paths/~1sdk-connections/get/responses/200 must have required property 'description'
  #/paths/~1sdk-connections/get/responses/200 must match "else" schema
  #/paths/~1sdk-connections~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1sdk-connections~1{id}/get/responses/200 must match "else" schema
  #/paths/~1data-sources/get/responses/200 must have required property 'description'
  #/paths/~1data-sources/get/responses/200 must match "else" schema
  #/paths/~1data-sources~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1data-sources~1{id}/get/responses/200 must match "else" schema
  #/paths/~1experiments/get/responses/200 must have required property 'description'
  #/paths/~1experiments/get/responses/200 must match "else" schema
  #/paths/~1experiments~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1experiments~1{id}/get/responses/200 must match "else" schema
  #/paths/~1experiments~1{id}~1results/get/responses/200 must have required property 'description'
  #/paths/~1experiments~1{id}~1results/get/responses/200 must match "else" schema
  #/paths/~1metrics/get/responses/200 must have required property 'description'
  #/paths/~1metrics/get/responses/200 must match "else" schema
  #/paths/~1metrics/post/responses/200 must have required property 'description'
  #/paths/~1metrics/post/responses/200 must match "else" schema
  #/paths/~1metrics~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1metrics~1{id}/get/responses/200 must match "else" schema
  #/paths/~1experiments~1{id}~1visual-changesets/get/parameters/0 must NOT have unevaluated properties
  #/paths/~1experiments~1{id}~1visual-changesets/get/parameters/0 must match "else" schema
  #/paths/~1experiments~1{id}~1visual-changesets/get/responses/200 must have required property 'description'
  #/paths/~1experiments~1{id}~1visual-changesets/get/responses/200 must match "else" schema
  #/paths/~1visual-changesets~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1visual-changesets~1{id}/get/responses/200 must match "else" schema
  #/paths/~1visual-changesets~1{id}/put/responses/200 must have required property 'description'
  #/paths/~1visual-changesets~1{id}/put/responses/200 must match "else" schema
  #/paths/~1visual-changesets~1{id}~1visual-change/post/responses/200 must have required property 'description'
  #/paths/~1visual-changesets~1{id}~1visual-change/post/responses/200 must match "else" schema
  #/paths/~1visual-changesets~1{id}~1visual-change~1{visualChangeId}/put/responses/200 must have required property 'description'
  #/paths/~1visual-changesets~1{id}~1visual-change~1{visualChangeId}/put/responses/200 must match "else" schema
  #/paths/~1saved-groups/get/responses/200 must have required property 'description'
  #/paths/~1saved-groups/get/responses/200 must match "else" schema
  #/paths/~1saved-groups/post/responses/200 must have required property 'description'
  #/paths/~1saved-groups/post/responses/200 must match "else" schema
  #/paths/~1saved-groups~1{id}/get/responses/200 must have required property 'description'
  #/paths/~1saved-groups~1{id}/get/responses/200 must match "else" schema
  #/paths/~1saved-groups~1{id}/post/responses/200 must have required property 'description'
  #/paths/~1saved-groups~1{id}/post/responses/200 must match "else" schema
  #/paths/~1saved-groups~1{id}/delete/responses/200 must have required property 'description'
  #/paths/~1saved-groups~1{id}/delete/responses/200 must match "else" schema
  #/components/responses/Error must have required property 'description'
  #/components/responses/Error must NOT have unevaluated properties
  #/components/responses/Error must NOT have unevaluated properties
  #/components/responses/Error must NOT have unevaluated properties
  #/components/responses/Error must match "else" schema

    at Function.o [as syntax] (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:95564)
    at validateSchema (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:6322)
    at SwaggerParser.validate (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:3391)
```

</details>

Check here for current results as the above stack trace may be out of date: https://apitools.dev/swagger-parser/online/?url=https%3A%2F%2Fapi.growthbook.io%2Fapi%2Fv1%2Fopenapi.yaml

Our OpenAPI spec should not have any errors.

Some possible things we can do in CI:

- Add OpenAPI validation to our CI checks

**Comment by tinahollygb** [comment]
The spec can still be used to generate code if we run it with validation disabled, but unfortunately it appears that it's generating invalid TypeScript. 

This is the tool used: https://www.npmjs.com/package/@openapitools/openapi-generator-cli

![CleanShot 2023-05-09 at 16 06 03@2x](https://github.com/growthbook/growthbook/assets/113377031/a0c1c323-61b1-4884-a78e-7031d236203c)

**Comment by tinahollygb** [comment]
FYI this is a branch for the CLI we can test the spec against: https://github.com/growthbook/growthbook-cli/tree/generate-openapi-client – It reads from `./tmp/openapi.yaml`

**Comment by tinahollygb** [comment]
FYI a workaround is to use the Axios generator instead of the fetch one: https://openapi-generator.tech/docs/generators/typescript-axios/

We should, however, still ship a valid file.

**Comment by jdorn** [comment]
The errors seem to be related to missing descriptions.  Closing this since it doesn't appear to be a blocker for anything.
