### ISSUE TITLE
Fail to start with docker compose: MongoDB connect error

### ISSUE THREAD

**Issue by d9k** [growthbook/growthbook#200]
```
> docker-compose up
Starting growthbook_mongo_1 ...
Starting growthbook_mongo_1 ... done
Starting growthbook_growthbook_1 ...
Starting growthbook_growthbook_1 ... done
Attaching to growthbook_mongo_1, growthbook_growthbook_1
mongo_1       |
mongo_1       | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
mongo_1       |   see https://jira.mongodb.org/browse/SERVER-54407
mongo_1       |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
mongo_1       |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
mongo_1       |
mongo_1       | /usr/local/bin/docker-entrypoint.sh: line 412:    28 Illegal instruction     (core dumped) "${mongodHackedArgs[@]}" --fork
growthbook_mongo_1 exited with code 132
growthbook_1  | yarn run v1.22.17
growthbook_1  | $ wsrun -p '*-end' -m start
growthbook_1  | back-end
growthbook_1  |  | $ node dist/server.js
growthbook_1  | front-end
growthbook_1  |  | $ next start
growthbook_1  |  | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
growthbook_1  |  | info  - Using webpack 5. Reason: no next.config.js https://nextjs.org/docs/messages/webpack5
growthbook_1  | back-end
growthbook_1  |  | No config.yml file. Using MongoDB instead to store data sources, metrics, and dimensions.
growthbook_1  |  |   Back-end is running at http://localhost:3100 in development mode
growthbook_1  |  |   Press CTRL-C to stop
growthbook_1  |  |
growthbook_1  |  | MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
growthbook_1  |  |     at NativeConnection.Connection.openUri (/usr/local/src/app/node_modules/mongoose/lib/connection.js:847:32)
growthbook_1  |  |     at /usr/local/src/app/node_modules/mongoose/lib/index.js:351:10
growthbook_1  |  |     at /usr/local/src/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
growthbook_1  |  |     at Promise._execute (/usr/local/src/app/node_modules/bluebird/js/release/debuggability.js:384:9)
growthbook_1  |  |     at Promise._resolveFromExecutor (/usr/local/src/app/node_modules/bluebird/js/release/promise.js:518:18)
growthbook_1  |  |     at new Promise (/usr/local/src/app/node_modules/bluebird/js/release/promise.js:103:10)
growthbook_1  |  |     at promiseOrCallback (/usr/local/src/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
growthbook_1  |  |     at Mongoose._promiseOrCallback (/usr/local/src/app/node_modules/mongoose/lib/index.js:1149:10)
growthbook_1  |  |     at Mongoose.connect (/usr/local/src/app/node_modules/mongoose/lib/index.js:350:20)
growthbook_1  |  |     at /usr/local/src/app/packages/back-end/dist/init/mongo.js:26:41
growthbook_1  |  |     at Generator.next (<anonymous>)
growthbook_1  |  |     at /usr/local/src/app/packages/back-end/dist/init/mongo.js:8:71
growthbook_1  |  |     at new Promise (<anonymous>)
growthbook_1  |  |     at __awaiter (/usr/local/src/app/packages/back-end/dist/init/mongo.js:4:12)
growthbook_1  |  |     at Object.exports.default (/usr/local/src/app/packages/back-end/dist/init/mongo.js:19:25)
growthbook_1  |  |     at /usr/local/src/app/packages/back-end/dist/app.js:94:38
growthbook_1  |  |     at Generator.next (<anonymous>)
growthbook_1  |  |     at /usr/local/src/app/packages/back-end/dist/app.js:27:71
growthbook_1  |  |     at new Promise (<anonymous>)
growthbook_1  |  |     at __awaiter (/usr/local/src/app/packages/back-end/dist/app.js:23:12)
growthbook_1  |  |     at /usr/local/src/app/packages/back-end/dist/app.js:93:34
growthbook_1  |  |     at /usr/local/src/app/packages/back-end/dist/app.js:96:16 {
growthbook_1  |  |   reason: TopologyDescription {
growthbook_1  |  |     type: 'Single',
growthbook_1  |  |     setName: null,
growthbook_1  |  |     maxSetVersion: null,
growthbook_1  |  |     maxElectionId: null,
growthbook_1  |  |     servers: Map(1) { 'mongo:27017' => [ServerDescription] },
growthbook_1  |  |     stale: false,
growthbook_1  |  |     compatible: true,
growthbook_1  |  |     compatibilityError: null,
growthbook_1  |  |     logicalSessionTimeoutMinutes: null,
growthbook_1  |  |     heartbeatFrequencyMS: 10000,
growthbook_1  |  |     localThresholdMS: 15,
growthbook_1  |  |     commonWireVersion: null
growthbook_1  |  |   }
growthbook_1  |  | }
growthbook_1  |  | Error: MongoDB connection error.
growthbook_1  |  |     at /usr/local/src/app/packages/back-end/dist/init/mongo.js:34:15
growthbook_1  |  |     at Generator.throw (<anonymous>)
growthbook_1  |  |     at rejected (/usr/local/src/app/packages/back-end/dist/init/mongo.js:6:65)
growthbook_1  |  | error Command failed with exit code 1.
growthbook_1  |  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
growthbook_1  |  | `yarn start` failed with exit code 1

> docker --version
Docker version 20.10.12, build e91ed57

> docker-compose --version
docker-compose version 1.17.1, build unknown
```

**Comment by jdorn** [comment]
From the error message, it looks like the latest MongoDB 5.0 does not support your OS
> WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!

We don't require any of the 5.0 features, so you should be able to simply modify `docker-compose.yml` and change `mongo:latest` to `mongo:4.4`

**Comment by d9k** [comment]
@jdorn, thanks, it runs with `mongo:4.4` :pray:

**Comment by d9k** [comment]
@jdorn, I wonder what is a market share of web developers CPUs without `AVX support`... If it's big enough, it would be nice to freeze MongoDB version in `docker-compose.yml`
