### ISSUE TITLE
[Bug]  How I can give a current status of growthbook (healthchecks)?

### ISSUE THREAD

**Issue by thejvmshid** [growthbook/growthbook#2238]
How can I connect healthcheck to get growthbook work status?

There is a healthcheck for growthbook-proxy (http://localhost:3300/healthcheck - https://docs.growthbook.io/self-host/proxy), but I couldn’t find one for growthbook.

Please tell me how can I get the status of growthbook itself?

Thanks for the heads up in advance.

**Comment by thejvmshid** [comment]
One moment:
`{"level":50,"time":1710743434070,"pid":58,"hostname":"growthbook-growthbook-chart-65dc578d67-4zhfj","err":{"type":"Error","message":"MongoDB connection error.","stack":"Error: MongoDB connection error.\n    at /usr/local/src/app/packages/back-end/dist/init/mongo.js:54:19\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/local/src/app/packages/back-end/dist/init/mongo.js:6:65)"},"msg":"Failed to initialize application"}
` - this is part of error, where growthbook can't connect to MongoDB. If I delete a Growthbook pod, application will continue works. If Growthbook API has a healthcheck

**Comment by thejvmshid** [comment]
In standalone, the problem may not arise and it will be difficult to imprint it. But the problem arises when the GB is lifted into Kubernetes.

**Comment by vanga** [comment]
I am also looking for information on any health endpoint that can be configured in the load balancer for health monitoring of the container/pod.

**Comment by wax911** [comment]
I don't know about specific endpoint but if you hit the API port (3100) by default it returns some json, so what I did was something rudimentary:

```yml
    healthcheck:
      test: ['CMD', 'wget', 'http://localhost:${API_PORT}']
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 10s
```

**Comment by jdorn** [comment]
The API server exposes a `GET /healthcheck` endpoint — see [Self-hosting → CDN](https://docs.growthbook.io/self-host/cdn). The GrowthBook Proxy exposes one too. Closing as implemented.
