### ISSUE TITLE
MongoDB Connection: srv protocol

### ISSUE THREAD

**Issue by benbenbang** [growthbook/growthbook#275]
Hi there,

since I am using vendor mongo from `AWS`, my default protocol is `mongodb+srv://` instead of `mongodb://`.
I've tried:
- `mongodb+srv://` with port -> `mongodb+srv:// URIs must not include a port number`
- without port -> `codeName: Unauthorized`

But I am sure the URI is good since I can connect to the mongo via `pymongo[srv]` with the same URI. Is it because you don't support the protocol? If so, could you please add it as soon as possible 🙏🏻 

Thanks for the help and your support again.

The full logs:
```
yarn run v1.22.17
$ wsrun -p '*-end' -m start
back-end
 | $ node dist/server.js
front-end
 | $ next start
 | warn  - You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env
 | warn  - You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env
 | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
 | info  - Using webpack 5. Reason: no next.config.js https://nextjs.org/docs/messages/webpack5
back-end
 | No config.yml file. Using MongoDB instead to store data sources, metrics, and dimensions.
 |   Back-end is running at http://localhost:3100 in dev mode
 |   Press CTRL-C to stop
 | 
 | /usr/local/src/app/node_modules/mongodb/lib/utils.js:698
 |           throw error;
 |           ^
 | 
 | MongoError: not authorized on test to execute command { createIndexes: "agendaJobs", indexes: [ { name: "findAndLockNextJobIndex", key: { name: 1, nextRunAt: 1, priority: -1, lockedAt: 1, disabled: 1 } } ], lsid: { id: UUID("a1806590-6f8c-440f-b924-05b749436201") }, $clusterTime: { clusterTime: Timestamp(1646159631, 12), signature: { hash: BinData(0, FA0538DCB987691A21C656941A8769727AF42ECD), keyId: 7028194452069941291 } }, $db: "test" }
 |     at MessageStream.messageHandler (/usr/local/src/app/node_modules/mongodb/lib/cmap/connection.js:299:20)
 |     at MessageStream.emit (events.js:400:28)
 |     at MessageStream.emit (domain.js:475:12)
 |     at processIncomingData (/usr/local/src/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
 |     at MessageStream._write (/usr/local/src/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
 |     at writeOrBuffer (internal/streams/writable.js:358:12)
 |     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
 |     at TLSSocket.ondata (internal/streams/readable.js:731:22)
 |     at TLSSocket.emit (events.js:400:28)
 |     at TLSSocket.emit (domain.js:475:12)
 |     at addChunk (internal/streams/readable.js:293:12)
 |     at readableAddChunk (internal/streams/readable.js:267:9)
 |     at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
 |     at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
 | Emitted 'error' event on Agenda instance at:
 |     at /usr/local/src/app/node_modules/agenda/dist/agenda/db-init.js:23:18
 |     at /usr/local/src/app/node_modules/mongodb/lib/utils.js:695:9
 |     at executeCallback (/usr/local/src/app/node_modules/mongodb/lib/operations/execute_operation.js:65:7)
 |     at /usr/local/src/app/node_modules/mongodb/lib/operations/create_indexes.js:126:9
 |     at /usr/local/src/app/node_modules/mongodb/lib/operations/command_v2.js:103:9
 |     at /usr/local/src/app/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
 |     at handleOperationResult (/usr/local/src/app/node_modules/mongodb/lib/core/sdam/server.js:567:5)
 |     at MessageStream.messageHandler (/usr/local/src/app/node_modules/mongodb/lib/cmap/connection.js:299:11)
 |     at MessageStream.emit (events.js:400:28)
 |     [... lines matching original stack trace ...]
 |     at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
 |   operationTime: Timestamp { _bsontype: 'Timestamp', low_: 12, high_: 1646159631 },
 |   ok: 0,
 |   code: 13,
 |   codeName: 'Unauthorized',
 |   '$clusterTime': {
 |     clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 12, high_: 1646159631 },
 |     signature: {
 |       hash: Binary {
 |         _bsontype: 'Binary',
 |         sub_type: 0,
 |         position: 20,
 |         buffer: Buffer(20) [Uint8Array] [
 |           250,   5,  56, 220, 185, 135,
 |           105,  26,  33, 198,  86, 148,
 |            26, 135, 105, 114, 122, 244,
 |            46, 205
 |         ]
 |       },
 |       keyId: Long { _bsontype: 'Long', low_: 43, high_: 1636379038 }
 |     }
 |   }
 | }
 | error Command failed with exit code 1.
 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | `yarn start` failed with exit code 1

```

The way I tested in python
``` python
import os
import pymongo
uri = os.getenv("MONGODB_URI")
print(uri)
client = pymongo.MongoClient(uri, port=27017)
# mongodb+srv://user-rw:pass@xxx.mongodb.net
client.list_database_names()
# ['xxx-growthbook-xxx]
```

**Comment by benbenbang** [comment]
To ppl who have the same issue:

This will work:
```
"mongodb+srv://username:password@host/database"
```
